Execute: RooSimplepTPbPb_split.cxx
	g++ RooSimplepTPbPb_split.cxx -o Execute \
		-I/afs/cern.ch/user/h/hbossi/RooUnfold/src -L/afs/cern.ch/user/h/hbossi/RooUnfold/ -lRooUnfold \
		`root-config --cflags --glibs`

ExecuteTrivial: RooSimplepTPbPb_trivial.cxx
	g++ RooSimplepTPbPb_trivial.cxx -o ExecuteTrivial \
		-I/afs/cern.ch/user/h/hbossi/RooUnfold/src -L/afs/cern.ch/user/h/hbossi/RooUnfold/ -lRooUnfold \
		`root-config --cflags --glibs`

ExecuteTrivial2D: RooSimplepTPbPb_Trivial2D.cxx
	g++ RooSimplepTPbPb_Trivial2D.cxx -o ExecuteTrivial2D \
		-I/afs/cern.ch/user/h/hbossi/RooUnfold/src -L/afs/cern.ch/user/h/hbossi/RooUnfold/ -lRooUnfold \
		`root-config --cflags --glibs`



Execute2D: RooSimplepTPbPb_split2D.cxx
	g++ RooSimplepTPbPb_split2D.cxx -o Execute2D \
		-I/afs/cern.ch/user/h/hbossi/RooUnfold/src -L/afs/cern.ch/user/h/hbossi/RooUnfold/ -lRooUnfold \
		`root-config --cflags --glibs`



Execute2DData: RooSimplepTPbPb_data2D.cxx
	g++ RooSimplepTPbPb_data2D.cxx -o Execute2DData \
		-I/afs/cern.ch/user/h/hbossi/RooUnfold/src -L/afs/cern.ch/user/h/hbossi/RooUnfold/ -lRooUnfold \
		`root-config --cflags --glibs`